SkillsTracker/Models/ErrorViewModel.cs
using System;

namespace SkillsTracker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SkillsTracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SkillsTracker.Models;

namespace SkillsTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SkillsTracker/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SkillsTracker.Controllers
{
    public class SkillsController : Controller
    {
        // GET: /<controller>/
       

        [HttpGet("skills")]
        public IActionResult Skills()
        {
            string html = "<h1> Skills Tracker </h1>" +
                          "<h2>Programming Languages</h2>"+
                          "<ol>" +
                          "<li>C#</li>" +
                          "<li>JavaScript</li>" +
                          "<li>Python</li>" +
                          "</ol>";
                
            return Content(html,"text/html");
        }

        [HttpGet("skills/form")]
        public IActionResult DisplayForm()
        {
            

            string html = "<form method='post' action='form/completed'>" +
                "<label for= 'date'> Date:</label>"+
                 "<input type='date' id = 'date' name='date' />" +
                 "<br>"+
                 "<label for='c'>C#</label>" +
                "<select name='c' id= 'c'>" +
                "<option value = 'Learning Basics' > Learning Basics </option>" +
                "<option value = 'Making Apps' > Making Apps </option>" +
                "<option value = 'Master Coder' >Master Coder</option>" +
                "</select>" +
                "<br>" +
                "<label for='j'>JavaScript</label>" +
                "<select name='j' id= 'j'>"+
                "<option value = 'Learning Basics' > Learning Basics </option>" +
                "<option value = 'Making Apps' > Making Apps </option>" +
                "<option value = 'Master Coder' >Master Coder</option>" +
                "</select>" +
                "<br>" +
                "<label for='p'>Python</label>" +
                "<select name='p' id= 'p'>"+
                "<option value = 'Learning Basics' > Learning Basics </option>" +
                "<option value = 'Making Apps' > Making Apps </option>" +
                "<option value = 'Master Coder' >Master Coder</option>" +
                "</select>" +
                "<br>" +
                "<input type='submit' value='Submit' />" +
                "</form>";

            return Content(html, "text/html");
        }


        [HttpPost("skills/form/completed")]
        public IActionResult Form(string date,string c,string j,string p)
        {
            string html = "<h1>"+date+"</h1>"+
                          "<ol>" +
                          "<li>C#: "+c+"</li>" +
                          "<li>JavaScript: "+j+"</li>" +
                          "<li>Python: " +p+"</li>" +
                          "</ol>";

            return Content(html, "text/html");
        }


    }
}

SkillsTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SkillsTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SkillsTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SkillsTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skills" asp-action="Skills">Skills</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skills" asp-action="DisplayForm">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SkillsTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SkillsTracker/Views/Skills/Skills.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Skills Tracker</h1>
<ol>
    <li>C#</li>
    <li>JavaScript</li>
    <li>Python</li>
</ol>